### ISSUE TITLE
How to scan only one directory?

### ISSUE THREAD

**Issue by v-adhithyan** [jayclassless/tidypy#33]
For example, I have following folders in my repo
app/
website/ 
docs/
etc.

I want to run tidypy in only app directory as a precommit hook. Please tell me how to achieve this.

**Comment by jayclassless** [comment]
You could use the "exclude" configuration parameter in your pyproject.toml file to exclude the directories you don't want TidyPy to dig into. [Take a look here](https://github.com/jayclassless/tidypy/blob/master/pyproject.toml#L7) for an example.
