### ISSUE TITLE
Unconfigurable report format

### ISSUE THREAD

**Issue by Densol92** [jayclassless/tidypy#34]
I try to use tidypy in Jenkins pipeline, pylint reporting. Jenkins expect format: {path}:{line}: [{msg_id}({symbol}), {obj}] {msg} 
tidypy use format '{type}:{line:>3},{character:>2}: {message} ({code}@{tool})'

I think it's pretty simple to add configurable reporting formatter.

**Comment by jayclassless** [comment]
I added a `pylint-parseable` reporter that emulates Pylint's "parseable" output, and also added a rough, initial implementation of a `custom` reporter that lets you specify your own format in the [project configuration](https://github.com/jayclassless/tidypy/blob/10358486fbd98716982ffca446866f2a5feec6d2/pyproject.toml#L21).

Hopefully one of those will help.

**Comment by Densol92** [comment]
Thanks a lot!
In the end i use pyproject.toml:
```
[[tool.tidypy.requested_reports]]
type = "custom"
format = "{filename}:{line}: [{code}({code}), ] {message}"
```
Jenkins config:
Post build actions : Scan for compiler warnings
Scan console log.
Parser: Pylint
