### ISSUE TITLE
pip install problem due to demjson dependency and incompatibility with setuptools >= 58.0

### ISSUE THREAD

**Issue by YoungPyDawan** [jayclassless/tidypy#78]
Due to removal of lib2to3 support in setuptools 
https://setuptools.readthedocs.io/en/latest/history.html#v58-0-0

demjson can no longer be installed with up-to-date packages so install of current tidypy fails.

A pin `setuptools<58.0` will work. Moving to demjson3 might also be an option.

**Comment by jayclassless** [comment]
Thanks for reporting. `0.21.1` should be more successful.
